### ISSUE TITLE
bots failing to compile on servers (multiple reports)

### ISSUE THREAD

**Issue by harikmenon** [HaliteChallenge/Halite-II#255]
Hi,

I am having some difficulty interpreting the reason for this failure (forwarded). The traceback emailed to me was

Traceback (most recent call last): File "worker.py", line 126, in executeCompileTask language, more_errors = compiler.compile_anything(temp_dir) File "/home/worker/Halite/apiserver/worker/compiler.py", line 601, in compile_anything detected_language, errors = detect_language(bot_dir) File "/home/worker/Halite/apiserver/worker/compiler.py", line 555, in detect_language with CD(bot_dir): File "/home/worker/Halite/apiserver/worker/compiler.py", line 35, in __enter__ self.org_dir = os.getcwd() FileNotFoundError: [Errno 2] No such file or directory 
Unfortunately I cannot understand why this occurs. Could you look into it?

**Comment by lidavidm** [comment]
It seems like the worker's current working directory is some directory that got removed (since we use a lot of temporary directories). I'm going to push something that just resets the working directory before compilation, and also make sure exceptions go into the worker log.

**Comment by lidavidm** [comment]
Also, it seems like that traceback comes from an old version of the worker, or at least, the line numbers don't match up.

**Comment by lidavidm** [comment]
Ah, it's probably in the archive code (which zips up the compiled bot) - if an exception occurs there for any reason, the CWD will get left inside the temp folder.
